# Import

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [13]:
import sys
from pathlib import Path

SRCPATH = Path.cwd()
ROOTPATH = SRCPATH.parent
DATA_DIR = ROOTPATH / "data"
LIB_DIR = ROOTPATH / "lib"
sys.path.insert(0, str(LIB_DIR))

from pandas_display import setup_pandas_display
from matplotlib_defaults import setup_matplotlib_defaults

setup_pandas_display()
setup_matplotlib_defaults()

# ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Import data

In [14]:
path = DATA_DIR / "messi_goals_all.csv"
df = pd.read_csv(path)

# データの概要を確認
print(df.shape)
display(df.head())
print(df.info())
display(df.describe())
display(df.describe(include=["object"]))

(896, 16)

,goal_index,date,competition_code,competition,home_team,away_team,result,minute_raw,minute_base,minute_added,minute_total,what,how,is_penalty,is_official,source_url
0,1,2005-05-01,PRM La Liga,PRM La Liga,FC Barcelona,Albacete,2-0,90,90,0,90,NaN,Left foot,0,1,https://www.messistats.com/en/locationsscored
1,2,2005-11-02,EUR UEFA Champions League,EUR UEFA Champions League,FC Barcelona,Panathinaikos,5-0,34,34,0,34,Field goal,Left foot,0,1,https://www.messistats.com/en/locationsscored
2,3,2005-11-27,PRM La Liga,PRM La Liga,FC Barcelona,Racing Santander,4-1,52,52,0,52,Field goal,Left foot,0,1,https://www.messistats.com/en/locationsscored
3,4,2006-01-15,PRM La Liga,PRM La Liga,FC Barcelona,Athletic de Bilbao,2-1,51,51,0,51,Rebound,Left foot,0,1,https://www.messistats.com/en/locationsscored
4,5,2006-01-22,PRM La Liga,PRM La Liga,FC Barcelona,Alavés,2-0,81,81,0,81,Rebound,Left foot,0,1,https://www.messistats.com/en/locationsscored

<class 'pandas.DataFrame'>
RangeIndex: 896 entries, 0 to 895
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   goal_index        896 non-null    int64
 1   date              896 non-null    str
 2   competition_code  896 non-null    str
 3   competition       896 non-null    str
 4   home_team         896 non-null    str
 5   away_team         896 non-null    str
 6   result            896 non-null    str
 7   minute_raw        896 non-null    str
 8   minute_base       896 non-null    int64
 9   minute_added      896 non-null    int64
 10  minute_total      896 non-null    int64
 11  what              618 non-null    str
 12  how               896 non-null    str
 13  is_penalty        896 non-null    int64
 14  is_official       896 non-null    int64
 15  source_url        896 non-null    str
dtypes: int64(6), str(10)
memory usage: 112.1 KB
None

,goal_index,minute_base,minute_added,minute_total,is_penalty,is_official
count,896,896,896,896,896,896
mean,448.5,51.84,0.1306,51.97,0.125,0.942
std,258.8,26.02,0.6427,26.18,0.3309,0.2339
min,1,2,0,2,0,0
25%,224.8,30,0,30,0,1
50%,448.5,54,0,54,0,1
75%,672.2,75,0,75,0,1
max,896,110,7,110,1,1

,date,competition_code,competition,home_team,away_team,result,minute_raw,what,how,source_url
count,896,896,896,896,896,896,896,618,896,896
unique,589,28,28,111,128,47,102,5,6,1
top,2012-03-07,PRM La Liga,PRM La Liga,FC Barcelona,FC Barcelona,4-0,87,Field goal,Left foot,https://www.messistats.com/en/locationsscored
freq,5,474,474,400,272,60,22,360,752,896